# Page settings
baseurl = "localhost:1313"
title = "TechOff Solutions"
languageCode = "en-us"
theme = "hugo-elate"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "xyybbqjb"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "TechOff Solutions"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About Us"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Enabling Business with Digital Innovation, Transformation, and Technology Adoption"
    subtitle = ''
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "We define your goals, understands and analyse business requirements, functions, features and other specifications are documented. Planning and strategy will be decided on the basis of project structure."
    url = "#"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "After documenting all the requirements, We move on to write a code using the best industry practices to produce a clean and user friendly website. We also make sure to inform you regularly about current status of the application."
    url = "#"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Hooray!!! Now its a time to show your presence in the digital world. Apart from that We provide free technical support for a period of time and are always available to make additions and improvements, as required. "
    url = "#"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "To show your presence and compete in digital world, you need an application. TechOff solutions provides below services which help to expand your business."

    [[params.services.item]]
      title = "Web Application & Development"
      description = "An average user interface and functionality will yield average results. Use full potential of the website using our web application & development service."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "e-Commerce Application Development"
      description = "Online shopping has now become a part of our economy and is been firmly established. We assure your customers able to shop on your website with ease and with confidence."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Support & Maintenance"
      description = "Increase your business productivity, add more features, flexibility and realize significant cost benefits to your business with innovative software application maintenance and enhancements."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About Us"
    description = "We know that every business work differently and our approach involves deep analysis and understanding of your business to create the right solution. We are well qualified to build, accelerate and innovate ideas in reality.."

    [[params.about.item]]
      name = "Vision"
      # position = "Web Designer"
      description = "To become well known organisation and fly in the cloud of technology to reach next level."
      img = "person1.jpg"
      alt = "Person1"
      #social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
      #  ["icon-linkedin", "#"]
      # ]

    [[params.about.item]]
      name = "Mission"
      # position = "Web Developer"
      description = "To deliver superior value and quality to our customers. Help customers to grow their business by providing innovative technological solution."
      img = "person2.jpg"
      alt = "Person2"
      #social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
      #  ["icon-linkedin", "#"]
      # ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "GET IN TOUCH WITH US !"
    description = "If you are looking for a website to grow your business and wants to show your presence in todays digital world or if you have an idea which you wants to be in reality, then you are landed on right location. So feel free to reach us and lets take off to fly in the IT world..."
    
    # Available icons: http://simplelineicons.com/
    details = [
        #["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "+91 9049193672/ 8208884729"],
        ["icon-envelope", "enquireforwebsite@gmail.com"],
        #["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
